# -*- coding: utf-8 -*-
"""Wordcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTpKhOfgu9JEdWQkhHj2o36Q59VbZJDa
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from PIL import Image
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import jieba
import numpy as np
from collections import Counter
# 如果檔案內有一些編碼錯誤，使用 errors='ignore' 來忽略錯誤
with open("cnyes_news.csv", encoding="Utf-8", errors='ignore') as f: text = f.read()

# 設定使用 big5 斷詞
jieba.set_dictionary('dict.txt.big.txt')
wordlist = jieba.cut(text)
words = " ".join(wordlist)

# 從 Google 下載的中文字型
font = 'SourceHanSansTW-Regular.otf'

#背景顏色預設黑色，改為白色、使用指定圖形、使用指定字體(一般文字雲)
#my_wordcloud = WordCloud(background_color='white',font_path=font).generate(words)

#文字雲造型圖片
mask = np.array(Image.open('star.jpg')) #文字雲形狀

#背景顏色預設黑色，改為白色、使用指定圖形、使用指定字體
my_wordcloud = WordCloud(background_color='white',mask=mask,font_path=font).generate(words)

#產生圖片
plt.figure(figsize=(6,6))
plt.imshow(my_wordcloud)
plt.axis("off")
plt.show()
#存檔
my_wordcloud.to_file('word_cloud.png')